import Foundation
import Publish
import Plot

struct SiteFooter: Component {
  var body: Component {
    Footer {
      Link(url: "/") {
        Image("/Image/Footer/footer-logo.svg")
      }
      .class("footer-logo")
      
      Link("Generated By", url: "https://github.com/johnsundell/publish")
        .class("footer-content")
      Link("License", url: "http://www.wtfpl.net/")
        .class("footer-content")
      Link("Contact", url: "/about")
        .class("footer-content")
    }
  }
}
