name: Build Output
on:
  pull_request:
    types: [labeled]

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  build-output:
    name: Build output
    runs-on: macos-latest
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'build output' }}
    steps:
      - name: Remove 'build output' label
        if: ${{ github.event.action == 'labeled' }}
        run: |
              curl \
              -X DELETE \
              -H 'Accept: application/vnd.github.v3+json' \
              -H 'Authorization: token ${{ github.token }}' \
              'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/build%20output'
      
#      - name: Checkout
#        uses: actions/checkout@v3
#      
#      - name: Set up Swift
#        uses: swift-actions/setup-swift@v2
#        with:
#          swift-version: "5.10.1"
#      
#      - name: Build Swift package
#        run: swift build --configuration release
#      
#      - name: Build Ignite site
#        run: .build/release/HogumachuWeb
      
      # - name: Setup Google Search File
      #   run: cp Includes/google6a751de03e3b3eb2.html Build/google6a751de03e3b3eb2.html
      
      - name: Push changes to the Build folder
        run: |
          git config --global user.name "Buildbot"
          git config --global user.email "buildbot@users.noreply.github.com"
          git add Build/*
          git commit -m "[BOT] build output for ${{ github.event.number }}"
          git push origin HEAD:${{ github.head_ref }} --force
