name: Build Output
on:
  pull_request:
    types: [labeled, ready_for_review]
    
defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}
    
jobs:
  build-output:
    name: Build output
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'build output' }}
    steps:
      - name: Remove 'build output' label
        if: ${{ github.event.action == 'labeled' }}
        run: |
          curl \
            -X DELETE \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'Authorization: token ${{ github.token }}' \
            'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/build%20output'
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Checkout Publish
        run: brew install publish
      - name: Build Publish site
        run: publish generate
      - name: Push changes to the Output folder
        run: |
          git config --global user.name "Buildbot"
          git config --global user.email "buildbot@users.noreply.github.com"
          git add Output/*
          git commit -m "[BOT] build output for ${{ github.event.number }}"
          git push origin HEAD:${{ github.head_ref }} --force
