name: Build Output
on:
  pull_request:
    types: [labeled]
    
defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}
    
jobs:
  build-output:
    name: Build output
    runs-on: macos-latest
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'build output' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Checkout Publish
        run: brew install publish
      - name: Build Publish site
        run: publish generate
      - name: Push changes to the Output folder
        run: |
          git config --global user.name "Buildbot"
          git config --global user.email "buildbot@users.noreply.github.com"
          git add Output/*
          git commit -m "[BOT] build output for ${{ github.event.number }}"
          git push origin HEAD:${{ github.head_ref }} --force
