name: Deploy
on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:
  
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Publish
        run: brew install publish
      - name: Build Publish site
        run: publish generate
      - name: Push Output folder to a git subtree for automatic deployment
        run: git push origin `git subtree split --prefix Output main`:production --force
